steps:
  # ── 1. Lint ────────────────────────────────────────────────────────────────
  # lint:
  #   image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
  #   when:
  #     branch: [main, dev]
  #     event: [push, pull_request]
  #   commands:
  #     - uv sync --dev --quiet
  #     - uv tool install ruff
  #     - uv tool install black
  #     - uv run ruff check app/
  #     - uv run black --check app/

  # ── 2. Tests (unit + API) ──────────────────────────────────────────────────
  # test:
  #   image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
  #   when:
  #     branch: [main, dev]
  #     event: [push, pull_request]
  #   environment:
  #     TEST_DATABASE_URL: postgresql://aiutox:aiutox@postgres:5432/aiutox_erp_test
  #     REDIS_URL: redis://redis:6379/0
  #     SECRET_KEY: ci-secret-key-not-for-production
  #     ENVIRONMENT: test
  #   commands:
  #     - apt-get update -qq && apt-get install -y -qq gcc postgresql-client
  #     - uv sync --dev --quiet
  #     - uv run pytest tests/ -v --tb=short --durations=10 -m "not performance"

  # ── 3. Build & push imagen Docker ─────────────────────────────────────────
  build-push:
    image: gcr.io/kaniko-project/executor:debug
    when:
      branch: main
      event: push
    commands:
      - echo '{"auths":{"registry:5000":{"username":"'$CI_REGISTRY_USERNAME'","password":"'$CI_REGISTRY_PASSWORD'"}}}' > /kaniko/.docker/config.json
      - /kaniko/executor --dockerfile=Dockerfile --destination=registry:5000/aiutox/backend:latest --destination=registry:5000/aiutox/backend:${CI_COMMIT_SHA} --cache=true

# services:
#   postgres:
#     image: postgres:16-alpine
#     environment:
#       POSTGRES_USER: aiutox
#       POSTGRES_PASSWORD: aiutox
#       POSTGRES_DB: aiutox_erp_test

#   redis:
#     image: redis:7-alpine

