"""Add delegated_permissions table

Revision ID: af20de189f20
Revises: 4d08f620a382
Create Date: 2025-12-09 21:06:53.652743+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af20de189f20'
down_revision: str | None = '4d08f620a382'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegated_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('permission', sa.String(length=255), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', 'permission', 'granted_by', name='uq_delegated_permissions_user_module_permission_granter')
    )
    # Indexes for efficient queries
    op.create_index('idx_delegated_permissions_user_id', 'delegated_permissions', ['user_id'], unique=False)
    op.create_index('idx_delegated_permissions_granted_by', 'delegated_permissions', ['granted_by'], unique=False)
    # Partial index for active permissions (not revoked)
    op.execute("""
        CREATE INDEX idx_delegated_permissions_active
        ON delegated_permissions (user_id, revoked_at, expires_at)
        WHERE revoked_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_delegated_permissions_active")
    op.drop_index('idx_delegated_permissions_granted_by', table_name='delegated_permissions')
    op.drop_index('idx_delegated_permissions_user_id', table_name='delegated_permissions')
    op.drop_table('delegated_permissions')
    # ### end Alembic commands ###

